export const DragSourceTypes = {
    TIME_CHART_ITEM: 'TIME_CHART_ITEM',
    TIME_CHART_ITEM_TEMPLATE: 'TIME_CHART_ITEM_TEMPLATE',
}

export const DropTargetTypes = {
    NON_OVERLAPPING_TIME_CHART: 'NON_OVERLAPPING_TIME_CHART',
    TIME_CHART_TEMPLATE_CONTAINER: 'TIME_CHART_TEMPLATE_CONTAINER',
}
